#ifndef SINTATICO_H_INCLUDED
#define SINTATICO_H_INCLUDED

void analisador_sintatico();
int corpo();
int programa();
int termo_program();
int cmd();
int var_dec();
int termo_var_dec();
int type();
int cond();
int termo_cond();
int fator_cond();
int iter();
int atrib();
int exp();
int exp_bool();
int A();
int termo_bool();
int B();
int fator_bool();
int exp_rel();
int C();
int exp_arit();
int D();
int termo_arit();
int E();
int fator_arit();
int list_func();
int list_param();
int param();
int ch_func();
int entrada();
int saida();
int concatenar();
void inicio_tex();
void fim_tex();

#endif // SINTATICO_H_INCLUDED
